FROM debian:bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*

COPY server ./server

# Create a directory for the database and ensure it has the correct permissions
RUN mkdir -p /data

ENV PORT=8080
ENV DB_DSN=/data/employees.db
EXPOSE 8080

CMD ["./server"]

